### ISSUE TITLE
[Suggestion] `rust_xlsxwriter` Crate for XLSX Output

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/tabelle#4]
I would like to suggest you this crate for writing XLSX files:  https://github.com/jmcnamara/rust_xlsxwriter.

It is dual-licensed MIT OR Apache-2.0, so it would fit this project well.  The crate is specialised exclusively on writing XLSX files but does so with extremely advanced options.  It is highly actively maintained; there are about two feature commits a day in an average week.  The idea would be to enhance the quality of the output XLSX files with this library at it is its specialty.

**Comment by wert007** [comment]
Hmm, but tabelle should be able to open xlsx files also, so I do not think it is a good fit here. The current crate for xlsx files is good enough I believe, we are not reaching its limits currently.

**Comment by kevinmatthes** [comment]
No problem.
